### BACKUP PROJECT PLAYBOOK ###

- name: Create Backup of current state of project
  hosts: otusproj
  #become: true
  gather_facts: false
  tasks:
  ### stop service before backup (cause ES indicies)
    - name: Stop nf-app before backup
      become: true
      tags:
        - stop
      systemd:
        name: nf-app
        state: stopped

  ### create dir for backups on local machine
    - name: Create Backup dir
      tags:
        - archive
      ansible.builtin.file:
        path: /home/artys/backups
        state: directory
  
  ### create backups of proj and images
    - name: Create Backup of current Project state
      community.general.archive:
         path: /home/artys/docker/otus-proj/.
         dest: /home/artys/backups/otus-proj.tgz

    - name: Archive all images as a tarball
      tags:
        - archive
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        archive_path: "/home/artys/backups/{{ item.path }}"
        source: local
      loop:
        - { name: 'docker.elastic.co/elasticsearch/elasticsearch', tag: '8.12.1', path: 'elasticsearch.tar' }
        - { name: 'docker.elastic.co/kibana/kibana', tag: '8.12.1', path: 'kibana.tar' }
        - { name: 'docker.elastic.co/beats/filebeat', tag: '8.12.1', path: 'filebeat.tar' }
        - { name: 'nginx', tag: 'latest', path: 'nginx.tar' }
      
    - name: Check backups are created in systemctl
      become: true
      tags:
        - check
      shell: ls -lah /home/artys/backups/
      register: result

    - name: Debug registered var
      tags:
        - check
      debug: var=result.stdout_lines

  ### copy backups to Ansible host
    - name: Copy all images to this host
      tags:
        - copy
      fetch:
        src: "/home/artys/backups/{{ item }}"
        dest: backups/
      loop: 
        - kibana.tar
        - elasticsearch.tar
        - nginx.tar
        - filebeat.tar
        - otus-proj.tgz
  ### run app after backup is completed
    - name: Enable & Start nf-app
      become: true
      tags:
        - start
      systemd:
        name: nf-app
        state: started
        enabled: yes
    
    - name: Check containers are up
      tags:
        - check
      shell: docker ps -a
      register: result
    
    - name: Debug registered var
      tags:
        - check
      debug: var=result.stdout_lines