### BACKUP PROJECT PLAYBOOK ###

- name: Create Backup of current state of project
  hosts: otusproj
  vars:
    user: artys
  gather_facts: yes
  tasks:
    - name: Display the current timestamp in YYYY-MM-DD
      debug:
        var=ansible_date_time.date

    - name: Create Ansible dir for backups
      ansible.builtin.file:
        path: backups/{{ ansible_date_time.date }}
        state: directory
      delegate_to: localhost
  ### stop service before backup (cause ES indicies)
    - name: Stop nf-app before backup
      become: true
      tags:
        - stop
      systemd:
        name: nf-app
        state: stopped

  ### create dir for backups on local machine
    - name: Create Backup dir
      tags:
        - archive
      ansible.builtin.file:
        path: "/home/{{ user }}/backups/"
        state: directory
  
  ### create backups of proj and images
    - name: Create Backup of current Project state
      community.general.archive:
         path: "/home/{{ user }}/docker/otus-proj/."
         dest: "/home/{{ user }}/backups/otus-proj.tgz"

    - name: Archive all images as a tarball
      tags:
        - archive
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        archive_path: "/home/{{ user }}/backups/{{ item.path }}"
        source: local
      loop:
        - { name: 'docker.elastic.co/elasticsearch/elasticsearch', tag: '8.12.1', path: 'elasticsearch.tar' }
        - { name: 'docker.elastic.co/kibana/kibana', tag: '8.12.1', path: 'kibana.tar' }
        - { name: 'docker.elastic.co/beats/filebeat', tag: '8.12.1', path: 'filebeat.tar' }
        - { name: 'nginx', tag: 'latest', path: 'nginx.tar' }
      
    - name: Check backups are created in systemctl
      become: true
      tags:
        - check
      shell: ls -lah /home/{{ user }}/backups/
      register: result

    - name: Debug registered var
      tags:
        - check
      debug: var=result.stdout_lines

  ### copy backups to Ansible host
    - name: Copy all images to this host
      tags:
        - copy
      fetch:
        src: "/home/{{ user }}/backups/{{ item }}"
   ### if want to put in "date" dir
        dest: backups/images/
        flat: yes
   #    dest: backups/
      loop: 
        - kibana.tar
        - elasticsearch.tar
        - nginx.tar
        - filebeat.tar

    - name: Copy project to this host
      tags:
        - copy
      fetch:
        src: "/home/{{ user }}/backups/otus-proj.tgz"
   ### if want to put in "date" dir
        dest: backups/{{ ansible_date_time.date }}/
        flat: yes  
      
  ### run app after backup is completed
    - name: Enable & Start nf-app
      become: true
      tags:
        - start
      systemd:
        name: nf-app
        state: started
        enabled: yes
    
    - name: Check containers are up
      tags:
        - check
      shell: docker ps -a
      register: result
    
    - name: Debug registered var
      tags:
        - check
      debug: var=result.stdout_lines