
- name: Run show commands on routers
  hosts: ios
  gather_facts: false

  tasks:

    - name: sh run
      cisco.ios.ios_command:
        commands: show running-config
      register: result

    - debug: var=result.stdout_lines

    # - name: run sh ip arp
    #   cisco.ios.ios_command:
    #     commands: sh ip arp
