---

- name: Create  directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop: 
    - "{{ repo_path }}"
    - "{{ distr_path }}"
    - "{{ mnt_path }}"
  
- name: Check if ISO exists
  stat:
    path: "{{ distr_path }}/{{ iso_file }}"
  register: iso_status

- name: Copy Astra Base-repo ISO
  when: not iso_status.stat.exists 
  copy:
    src: "{{ iso_file }}"
    dest: "{{ distr_path }}"
    remote_src: no

- name: Check if source.list file exists
  stat:
    path: "/etc/apt/sources.list"
  register: sources_status

- name: Move old sources.apt
  when: sources_status.stat.exists
  command: mv /etc/apt/sources.list /etc/apt/sources.list_OLD

- name: Mount BASE-repo ISO read-only
  mount:
    path: "{{ mnt_path }}"
    src: "{{ distr_path }}/{{ iso_file }}"
    fstype: iso9660
    opts: ro
    state: mounted

- name: Copy Astra Base repo from ISO
  copy:
    src: "{{ mnt_path }}/"
    dest: "{{ repo_path }}"
    remote_src: yes
    owner: kii
    group: kii
    mode: '0777'
    
- name: Unmount a mounted volume
  mount:
    path: "{{ mnt_path }}"
    state: absent

- name: Copy APT sources.list
  copy:
    src: sources.list
    dest: /etc/apt/
    remote_src: no
  
- name: apt-get update
  apt:
     update_cache: yes

- name: Remove ISO
  file:
    path: "{{ distr_path }}/{{ iso_file }}"
    state: absent
