- name: Config new machine
  hosts: otusproj
  vars:
    user: artys
    date: '2024-03-08' ### change this to right date of backup
  gather_facts: false
  
  tasks:

    - name: Copy docker-repo to yum.repos.d
      become: true
      tags:
        - setup
      ansible.builtin.copy:
        src: docker-ce.repo
        dest: /etc/yum.repos.d
        remote_src: no

  ### install docker and cockpit to monitoring containers state
    - name: DNF Update
      become: true
      tags:
        - setup
      ansible.builtin.dnf:
        update_cache: yes

    - name: Upgrade all packages
      become: true
      tags:
        - setup
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install Docker, Docker-Compose, Cockpit
      become: true
      tags:
        - setup
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - cockpit
        - cockpit-machines
        - cockpit-storaged
        - cockpit-pcp
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - git
  
    - name: Copy cockpit-docker.tar.gz
      become: true
      tags:
        - setup
      copy:
        src: cockpit-docker.tar.gz
        dest: /usr/share/cockpit
        remote_src: no
        mode: 0644
        owner: root
        group: root

    - name: Stop docker
      tags:
        - config
      become: true
      systemd:
        name: docker.socket
        state: stopped

    - name: Rm old backup
      ansible.builtin.file:
        path: "/home/{{ user }}/restore"
        state: absent
    
    - name: Rm old project
      become: true
      ansible.builtin.file:
        path: "/home/{{ user }}/nf-app"
        state: absent
   
    - name: Unarchive cockpit-docker.tar.gz
      become: true
      tags:
        - setup
      unarchive:
        src: /usr/share/cockpit/cockpit-docker.tar.gz
        dest: /usr/share/cockpit/
        remote_src: yes

    - name: List installed packages
      tags:
        - setup
      shell: dnf list installed | grep -E "git|cockpit|cockpit-machines|cockpit-storaged|cockpit-pcp|docker-ce-cli|docker-ce|docker-compose-plugin"
      register: result
    - debug: var=result.stdout_lines
      tags:
        - setup

      ### there is no need to use IPv6 in this project and this part used to run init.sh correct
    - name: Disable IPv6 with sysctl
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      tags:
        - config
      with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

    - name: Enable & Start cockpit.socket
      become: true
      tags:
        - setup
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes
    
    - name: Enable & Start pmlogger.service
      become: true
      tags:
        - setup
      systemd:
        name: pmlogger.service
        state: started
        enabled: yes

    - name: Create dir to import Backups
      tags:
        - config
      ansible.builtin.file:
        path: "/home/{{ user }}/restore"
        state: directory
            
  # copy all backups to new machine
    - name: Copy Images Backup to New Host
      tags:
        - copy
      copy:
        src: "backups/images/nf-images.tar"
        dest: "/home/{{ user }}/restore/"
    
    - name: Copy Project Backup to New Host
      tags:
        - copy
      copy:
        src: "backups/{{ date }}/nf-app.tgz"
        dest: "/home/{{ user }}/restore/"

  ### add user to group docker  
    - name: add user to docker group
      become: true
      tags:
         - configuration
      user:
        name: "{{ user }}"
        comment: "{{ user }}"
        groups: "{{ user }}, wheel, docker"
        append: yes

    - name: Reset connection to reapply groups to user
      meta: reset_connection
      
    
    - name: Create docker dir in home
      tags:
        - copy
      file:
        path: "/home/{{ user }}/nf-app"
        state: directory
  
    - name: Unarchive project to this directory
      tags:
        - copy
      unarchive:
        src: "/home/{{ user }}/restore/nf-app.tgz"
        dest: "/home/{{ user }}/nf-app"
        remote_src: yes

    - name: Enable & Start docker
      tags:
        - config
      become: true
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Load all image(s) from the given tar files
      tags:
        - docker
      community.docker.docker_image_load:
        path: "/home/{{ user }}/restore/nf-images.tar"
      register: result
      timeout: 300
    
    - debug: var=result.stdout_lines
      tags:
        - pre

  ### change IP addresses in .env ###
    
    - name: Run init.sh to change MAIN_IP and DNS_IP in .env
      tags:
        - config
      shell: sh init.sh
      args:
        chdir: "/home/{{ user }}/nf-app/"
  
    - name: Run app from docker-compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ user }}/nf-app/"
        files:
        - docker-compose.yml
        state: present
    
    - name: Check containers are up
      tags:
        - check
      shell: docker ps -a
      register: result
    - debug: var=result.stdout_lines
    
